/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ReportsMonthlyMonthRouteImport } from './routes/reports.monthly.$month'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks/resend'
import { Route as ApiCronIndexnowRouteImport } from './routes/api/cron/indexnow'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsMonthlyMonthRoute = ReportsMonthlyMonthRouteImport.update({
  id: '/monthly/$month',
  path: '/monthly/$month',
  getParentRoute: () => ReportsRoute,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronIndexnowRoute = ApiCronIndexnowRouteImport.update({
  id: '/api/cron/indexnow',
  path: '/api/cron/indexnow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/policy': typeof PolicyRoute
  '/ports': typeof PortsRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/reports/': typeof ReportsIndexRoute
  '/api/cron/indexnow': typeof ApiCronIndexnowRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/reports/monthly/$month': typeof ReportsMonthlyMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/policy': typeof PolicyRoute
  '/ports': typeof PortsRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/reports': typeof ReportsIndexRoute
  '/api/cron/indexnow': typeof ApiCronIndexnowRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/reports/monthly/$month': typeof ReportsMonthlyMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/policy': typeof PolicyRoute
  '/ports': typeof PortsRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/reports/': typeof ReportsIndexRoute
  '/api/cron/indexnow': typeof ApiCronIndexnowRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/reports/monthly/$month': typeof ReportsMonthlyMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/methodology'
    | '/news'
    | '/policy'
    | '/ports'
    | '/privacy'
    | '/rates'
    | '/reports'
    | '/sitemap.xml'
    | '/trade'
    | '/unsubscribe'
    | '/article/$slug'
    | '/reports/'
    | '/api/cron/indexnow'
    | '/api/webhooks/resend'
    | '/reports/monthly/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/methodology'
    | '/news'
    | '/policy'
    | '/ports'
    | '/privacy'
    | '/rates'
    | '/sitemap.xml'
    | '/trade'
    | '/unsubscribe'
    | '/article/$slug'
    | '/reports'
    | '/api/cron/indexnow'
    | '/api/webhooks/resend'
    | '/reports/monthly/$month'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/methodology'
    | '/news'
    | '/policy'
    | '/ports'
    | '/privacy'
    | '/rates'
    | '/reports'
    | '/sitemap.xml'
    | '/trade'
    | '/unsubscribe'
    | '/article/$slug'
    | '/reports/'
    | '/api/cron/indexnow'
    | '/api/webhooks/resend'
    | '/reports/monthly/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  MethodologyRoute: typeof MethodologyRoute
  NewsRoute: typeof NewsRoute
  PolicyRoute: typeof PolicyRoute
  PortsRoute: typeof PortsRoute
  PrivacyRoute: typeof PrivacyRoute
  RatesRoute: typeof RatesRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradeRoute: typeof TradeRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  ApiCronIndexnowRoute: typeof ApiCronIndexnowRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/monthly/$month': {
      id: '/reports/monthly/$month'
      path: '/monthly/$month'
      fullPath: '/reports/monthly/$month'
      preLoaderRoute: typeof ReportsMonthlyMonthRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/indexnow': {
      id: '/api/cron/indexnow'
      path: '/api/cron/indexnow'
      fullPath: '/api/cron/indexnow'
      preLoaderRoute: typeof ApiCronIndexnowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsIndexRoute: typeof ReportsIndexRoute
  ReportsMonthlyMonthRoute: typeof ReportsMonthlyMonthRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIndexRoute: ReportsIndexRoute,
  ReportsMonthlyMonthRoute: ReportsMonthlyMonthRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  MethodologyRoute: MethodologyRoute,
  NewsRoute: NewsRoute,
  PolicyRoute: PolicyRoute,
  PortsRoute: PortsRoute,
  PrivacyRoute: PrivacyRoute,
  RatesRoute: RatesRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradeRoute: TradeRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  ApiCronIndexnowRoute: ApiCronIndexnowRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
